import React from 'react'
import { MDXProvider } from '@mdx-js/react'
import {
  Accordion,
  Alert,
  AlertDialog,
  Avatar,
  AspectRatioBox,
  AvatarGroup,
  Badge,
  Box,
  Breadcrumb,
  Button,
  ButtonGroup,
  Callout,
  Code,
  Checkbox,
  CheckboxGroup,
  CloseButton,
  Collapse,
  ControlBox,
  CircularProgress,
  Divider,
  Drawer,
  Editable,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  FormErrorMessage,
  Grid,
  Heading,
  Icon,
  IconButton,
  Image,
  Input,
  InputAddon,
  InputGroup,
  Kbd,
  Link,
  List,
  ListItem,
  Stack,
  SimpleGrid,
  Menu,
  Modal,
  NumberInput,
  Portal,
  Popover,
  Progress,
  PseudoBox,
  Radio,
  RadioGroup,
  RadioButtonGroup,
  Select,
  Skeleton,
  Slider,
  Spinner,
  Stat,
  Switch,
  Tabs,
  Tag,
  Text,
  Textarea,
  Tooltip,
  VisuallyHidden,
} from '@chakra-ui/core'

const mdComponents = {
  h1: (props) => <Heading as="h1" mb={4} {...props} />,
  h2: (props) => <Heading as="h2" my={4} {...props} />,
  h3: (props) => <Heading as="h3" my={4} {...props} />,
  h4: (props) => <Heading as="h4" my={4} {...props} />,
  p: (props) => <Text as="p" mb={4} {...props} />,
  a: (props) => <Link as="a" {...props} />,
  pre: (props) => <Box as="pre" p={2} mb={4} {...props} />,
  code: (props) => <Code {...props} />,
  ul: (props) => <List px={3} styleType="square" {...props} />,
  ol: (props) => <List as="ol" styleType="decimal" {...props} />,
  li: (props) => <ListItem {...props} />,
  img: (props) => <Image width="100%" {...props} />,
  hr: (props) => <Divider my={8} {...props} />,
  Accordion,
  Alert,
  AlertDialog,
  Avatar,
  AspectRatioBox,
  AvatarGroup,
  Badge,
  Box,
  Breadcrumb,
  Button,
  ButtonGroup,
  Callout,
  Code,
  Checkbox,
  CheckboxGroup,
  CloseButton,
  Collapse,
  ControlBox,
  CircularProgress,
  Divider,
  Drawer,
  Editable,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  FormErrorMessage,
  Grid,
  Heading,
  Icon,
  IconButton,
  Image,
  Input,
  InputAddon,
  InputGroup,
  Kbd,
  Link,
  List,
  Stack,
  SimpleGrid,
  Menu,
  Modal,
  NumberInput,
  Portal,
  Popover,
  Progress,
  PseudoBox,
  Radio,
  RadioGroup,
  RadioButtonGroup,
  Select,
  Skeleton,
  Slider,
  Spinner,
  Stat,
  Switch,
  Tabs,
  Tag,
  Text,
  Textarea,
  Tooltip,
  VisuallyHidden,
}

export default ({ children }) => (
  <MDXProvider components={mdComponents}>{children}</MDXProvider>
)
